### ISSUE TITLE
uvicorn[standard]===0.30.1 lib is not supported by v0.2.0 its uvicorn process getting killed.

### ISSUE THREAD

**Issue by thangaraj-HPE** [aws-observability/aws-otel-python-instrumentation#228]
```
2024-07-17T17:16:05.354Z | INFO: Waiting for child process [23]
-- | --
  | 2024-07-17T17:16:05.361Z | INFO: Child process [23] died
  | 2024-07-17T17:16:08.115Z | AwsEc2ResourceDetector failed: <urlopen error [Errno 22] Invalid argument>
  | 2024-07-17T17:16:08.116Z | Failed to get k8s token: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:08.116Z | AwsEksResourceDetector failed: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:08.290Z | Configuration of configurator not loaded, aws_configurator already loaded
  | 2024-07-17T17:16:08.989Z | AwsEc2ResourceDetector failed: <urlopen error [Errno 22] Invalid argument>
  | 2024-07-17T17:16:08.990Z | Failed to get k8s token: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:08.990Z | AwsEksResourceDetector failed: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:09.183Z | Configuration of configurator not loaded, aws_configurator already loaded
  | 2024-07-17T17:16:10.366Z | INFO: Waiting for child process [24]
  | 2024-07-17T17:16:10.384Z | INFO: Child process [24] died
  | 2024-07-17T17:16:10.892Z | INFO: Waiting for child process [24]
  | 2024-07-17T17:16:10.892Z | INFO: Child process [24] died
  | 2024-07-17T17:16:12.995Z | AwsEc2ResourceDetector failed: <urlopen error [Errno 22] Invalid argument>
  | 2024-07-17T17:16:12.995Z | Failed to get k8s token: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:12.995Z | AwsEksResourceDetector failed: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'
  | 2024-07-17T17:16:13.168Z | Configuration of configurator not loaded, aws_configurator already loaded
  | 2024-07-17T17:16:15.899Z | INFO: Waiting for child process [53]
  | 2024-07-17T17:16:15.905Z | INFO: Child process [53] died

```

**Comment by thpierce** [comment]
Hi @thangaraj-HPE - thanks for reaching out. My understanding is that you have an application that uses `uvicorn[standard]===0.30.1` and that attempting to use ADOT Python Autoinstrumentation v0.2.0 causes your application to fail.

Can you share a bit more information? Specifically:
1. What commands are you using to run the instrumentation?
2. What platform are you running on? EC2, EKS, something else?
3. Can you share any additional detail about your application, what other frameworks it is using, etc.?
4. Are you able to reproduce this issue with v0.3.0, which was just recently released and brings in many changes from OTEL?
5. Are you able to reproduce this issue with the [OTEL Distro](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-distro)?

Thanks!

**Comment by thangaraj-HPE** [comment]
1. I did follow the below documents for enabling  instrumentation.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Signals-Enable-ECS.html
2. its on ECS fargate.
3. we use fast-api and uvivron with our application.
4. i have test it with version v0.3.0. Thansk for release.
5. I didn't try with OTEL Distro. since i need it on AWS ECS.

**Comment by thpierce** [comment]
> i have test it with version v0.3.0. Thansk for release.

Just to clarify, the issue still exists with v0.3.0?

**Comment by thangaraj-HPE** [comment]
sorry i have not yet test it with version v0.3.0. will keep you updated in couple of days on this. Thanks

**Comment by thpierce** [comment]
I'm going to close out this issue @ this time. Please feel free to re-open if you are still seeing this issue.
